// عبارات بحث بالعنوان الأصلي/الإنجليزي لكل كتاب — تُستخدم للبحث في Open Library عن الغلاف الحقيقي.
// null تعني: عنوان لا يقابل عملاً منشورًا حقيقيًا قابلًا للتحقق (سيبقى الغلاف الملوّن الافتراضي).
export const COVER_QUERIES = {
  1: "One Hundred Years of Solitude Gabriel Garcia Marquez",
  2: "Men in the Sun Ghassan Kanafani",
  3: "The Bamboo Stalk Saud Alsanousi",
  4: "Cities of Salt Abdelrahman Munif",
  5: "The Da Vinci Code Dan Brown",
  6: "Sophie's World Jostein Gaarder",
  7: "The Power of Now Eckhart Tolle",
  8: "The Hound of the Baskervilles Arthur Conan Doyle",
  9: "Azazeel Youssef Ziedan",
  10: "Frankenstein in Baghdad Ahmed Saadawi",
  11: "The Forty Rules of Love Elif Shafak",
  12: "Fahrenheit 451 Ray Bradbury",
  13: "The Notebook Nicholas Sparks",
  14: "Harry Potter and the Philosopher's Stone Rowling",
  15: "Crime and Punishment Fyodor Dostoevsky",
  16: "War and Peace Leo Tolstoy",
  17: "Les Miserables Victor Hugo",
  18: "Animal Farm George Orwell",
  19: "Nineteen Eighty-Four George Orwell",
  20: "The Old Man and the Sea Ernest Hemingway",
  21: "The Stranger Albert Camus",
  22: "The Little Prince Antoine de Saint-Exupery",
  23: "Pride and Prejudice Jane Austen",
  24: "Wuthering Heights Emily Bronte",
  25: "Anna Karenina Leo Tolstoy",
  26: "Dracula Bram Stoker",
  27: "Frankenstein Mary Shelley",
  28: "The Alchemist Paulo Coelho",
  29: "Little Women Louisa May Alcott",
  30: "Memory in the Flesh Ahlam Mosteghanemi",
  31: "Granada Radwa Ashour",
  32: "Children of Gebelawi Naguib Mahfouz",
  33: "Palace Walk Naguib Mahfouz",
  34: "Season of Migration to the North Tayeb Salih",
  35: "The Harafish Naguib Mahfouz",
  36: "Diamond Dust Ahmed Mourad",
  37: "The Blue Elephant Ahmed Mourad",
  38: "1919 Ahmed Mourad",
  39: "Sunset Oasis Bahaa Taher",
  40: "East of the Mediterranean Abdul Rahman Munif",
  41: "Murder on the Orient Express Agatha Christie",
  42: "And Then There Were None Agatha Christie",
  43: "The Girl with the Dragon Tattoo Stieg Larsson",
  44: "Brave New World Aldous Huxley",
  45: "Sapiens Yuval Noah Harari",
  46: "Thinking Fast and Slow Daniel Kahneman",
  47: "The 7 Habits of Highly Effective People Stephen Covey",
  48: "The Subtle Art of Not Giving a F*ck Mark Manson",
  49: "The Power of Habit Charles Duhigg",
  50: "The Monk Who Sold His Ferrari Robin Sharma",
};
